### ISSUE TITLE
Can not display the correct value in big card menu

### ISSUE THREAD

**Issue by rainfoxest** [NekoCaffeine/sts-fix#1]
![20190129155343_1](https://user-images.githubusercontent.com/31983538/51892860-257a6180-23de-11e9-8ee5-8e44d58f44ad.jpg)
![20190129155350_1](https://user-images.githubusercontent.com/31983538/51892861-2612f800-23de-11e9-86d4-62bffdca8b30.jpg)
![20190129155351_1](https://user-images.githubusercontent.com/31983538/51892862-2612f800-23de-11e9-9c7d-82271481b0e6.jpg)
![20190129155451_1](https://user-images.githubusercontent.com/31983538/51892888-3925c800-23de-11e9-8038-94a27c851ff7.jpg)

**Comment by NekoCaffeine** [comment]
fixed: c9fa1a1011848465ef7133198f8cb0a6882721be
https://github.com/NekoCaffeine/sts-fix/releases/tag/1.0.1
