### ISSUE TITLE
请问能支持mac吗

### ISSUE THREAD

**Issue by whwq2012** [NekoCaffeine/sts-fix#2]
我把这个jar包复制到STS的content里执行，但是提示找不到文件，是我使用方式不对，还是还未支持mac系统呢？

**Comment by NekoCaffeine** [comment]
我没有mac的机子我没法测试也不知道mac上的环境和路径是怎么样的，但是这个jar本身是可以在mac上运行的，你只说提示找不到文件我也不知道发生了什么。windows上STS的相对目录"steamapps\common\SlayTheSpire"下会有个"jre"，我是相对于这个jre写了个bat来运行jar文件的，然后那个jar是要求放在根目录的，也就是上面提到的那个相对目录，我不知道mac上的差异。你还可以用“java -jar xxx.jar”来执行一个jar文件，比如执行我的修复补丁。

**Comment by whwq2012** [comment]
>.
└── SlayTheSpire
    ├── SlayTheSpire.app
    │   └── Contents
    │       ├── Info.plist
    │       ├── MacOS
    │       │   ├── SlayTheSpire
    │       │   └── SlayTheSpireTroubleshoot.sh
    │       └── Resources
    │           ├── README.md
    │           ├── betaPreferences
    │           │   ├── STSAchievements
    │           │   ├── STSAchievements.backUp
    │           │   ├── STSBetaCardPreference
    │           │   ├── STSDaily
    │           │   ├── STSDaily.backUp
    │           │   ├── STSDataDefect
    │           │   ├── STSDataDefect.backUp
    │           │   ├── STSDataTheSilent
    │           │   ├── STSDataTheSilent.backUp
    │           │   ├── STSDataVagabond
    │           │   ├── STSDataVagabond.backUp
    │           │   ├── STSGameplaySettings
    │           │   ├── STSGameplaySettings.backUp
    │           │   ├── STSInputSettings
    │           │   ├── STSInputSettings_Controller
    │           │   ├── STSPlayer
    │           │   ├── STSPlayer.backUp
    │           │   ├── STSSaveSlots
    │           │   ├── STSSaveSlots.backUp
    │           │   ├── STSSeenBosses
    │           │   ├── STSSeenBosses.backUp
    │           │   ├── STSSeenCards
    │           │   ├── STSSeenCards.backUp
    │           │   ├── STSSeenRelics
    │           │   ├── STSSeenRelics.backUp
    │           │   ├── STSSound
    │           │   ├── STSSound.backUp
    │           │   ├── STSTips
    │           │   ├── STSTips.backUp
    │           │   ├── STSUnlockProgress
    │           │   ├── STSUnlockProgress.backUp
    │           │   ├── STSUnlocks
    │           │   └── STSUnlocks.backUp
    │           ├── config.json
    │           ├── desktop-1.0.jar
    │           ├── icons.icns
    │           ├── info.displayconfig
    │           ├── jre
    │           │   ├── COPYRIGHT
    │           │   ├── LICENSE
    │           │   ├── README
    │           │   ├── THIRDPARTYLICENSEREADME-JAVAFX.txt
    │           │   ├── THIRDPARTYLICENSEREADME.txt
    │           │   ├── Welcome.html
    │           │   ├── bin
    │           │   │   ├── java
    │           │   │   ├── jjs
    │           │   │   ├── keytool
    │           │   │   ├── orbd
    │           │   │   ├── pack200
    │           │   │   ├── policytool
    │           │   │   ├── rmid
    │           │   │   ├── rmiregistry
    │           │   │   ├── servertool
    │           │   │   ├── tnameserv
    │           │   │   └── unpack200
    │           │   ├── lib
    │           │   │   ├── applet
    │           │   │   ├── calendars.properties
    │           │   │   ├── charsets.jar
    │           │   │   ├── classlist
    │           │   │   ├── cmm
    │           │   │   │   ├── CIEXYZ.pf
    │           │   │   │   ├── GRAY.pf
    │           │   │   │   ├── LINEAR_RGB.pf
    │           │   │   │   ├── PYCC.pf
    │           │   │   │   └── sRGB.pf
    │           │   │   ├── content-types.properties
    │           │   │   ├── currency.data
    │           │   │   ├── ext
    │           │   │   │   ├── cldrdata.jar
    │           │   │   │   ├── dnsns.jar
    │           │   │   │   ├── jaccess.jar
    │           │   │   │   ├── jfxrt.jar
    │           │   │   │   ├── localedata.jar
    │           │   │   │   ├── meta-index
    │           │   │   │   ├── nashorn.jar
    │           │   │   │   ├── sunec.jar
    │           │   │   │   ├── sunjce_provider.jar
    │           │   │   │   ├── sunpkcs11.jar
    │           │   │   │   └── zipfs.jar
    │           │   │   ├── flavormap.properties
    │           │   │   ├── fontconfig.bfc
    │           │   │   ├── fontconfig.properties.src
    │           │   │   ├── fonts
    │           │   │   │   ├── LucidaBrightDemiBold.ttf
    │           │   │   │   ├── LucidaBrightDemiItalic.ttf
    │           │   │   │   ├── LucidaBrightItalic.ttf
    │           │   │   │   ├── LucidaBrightRegular.ttf
    │           │   │   │   ├── LucidaSansDemiBold.ttf
    │           │   │   │   ├── LucidaSansRegular.ttf
    │           │   │   │   ├── LucidaTypewriterBold.ttf
    │           │   │   │   ├── LucidaTypewriterRegular.ttf
    │           │   │   │   └── fonts.dir
    │           │   │   ├── hijrah-config-umalqura.properties
    │           │   │   ├── images
    │           │   │   │   └── cursors
    │           │   │   │       ├── cursors.properties
    │           │   │   │       ├── invalid32x32.gif
    │           │   │   │       ├── motif_CopyDrop32x32.gif
    │           │   │   │       ├── motif_CopyNoDrop32x32.gif
    │           │   │   │       ├── motif_LinkDrop32x32.gif
    │           │   │   │       ├── motif_LinkNoDrop32x32.gif
    │           │   │   │       ├── motif_MoveDrop32x32.gif
    │           │   │   │       └── motif_MoveNoDrop32x32.gif
    │           │   │   ├── javafx.properties
    │           │   │   ├── jce.jar
    │           │   │   ├── jfr
    │           │   │   │   ├── default.jfc
    │           │   │   │   └── profile.jfc
    │           │   │   ├── jfr.jar
    │           │   │   ├── jfxswt.jar
    │           │   │   ├── jli
    │           │   │   │   └── libjli.dylib
    │           │   │   ├── jspawnhelper
    │           │   │   ├── jsse.jar
    │           │   │   ├── jvm.cfg
    │           │   │   ├── jvm.hprof.txt
    │           │   │   ├── libAppleScriptEngine.dylib
    │           │   │   ├── libattach.dylib
    │           │   │   ├── libawt.dylib
    │           │   │   ├── libawt_lwawt.dylib
    │           │   │   ├── libbci.dylib
    │           │   │   ├── libdcpr.dylib
    │           │   │   ├── libdecora_sse.dylib
    │           │   │   ├── libdt_socket.dylib
    │           │   │   ├── libfontmanager.dylib
    │           │   │   ├── libfxplugins.dylib
    │           │   │   ├── libglass.dylib
    │           │   │   ├── libglib-lite.dylib
    │           │   │   ├── libgstreamer-lite.dylib
    │           │   │   ├── libhprof.dylib
    │           │   │   ├── libinstrument.dylib
    │           │   │   ├── libj2gss.dylib
    │           │   │   ├── libj2pcsc.dylib
    │           │   │   ├── libj2pkcs11.dylib
    │           │   │   ├── libjaas_unix.dylib
    │           │   │   ├── libjava.dylib
    │           │   │   ├── libjava_crw_demo.dylib
    │           │   │   ├── libjavafx_font.dylib
    │           │   │   ├── libjavafx_font_t2k.dylib
    │           │   │   ├── libjavafx_iio.dylib
    │           │   │   ├── libjawt.dylib
    │           │   │   ├── libjdwp.dylib
    │           │   │   ├── libjfr.dylib
    │           │   │   ├── libjfxmedia.dylib
    │           │   │   ├── libjfxmedia_avf.dylib
    │           │   │   ├── libjfxmedia_qtkit.dylib
    │           │   │   ├── libjfxwebkit.dylib
    │           │   │   ├── libjpeg.dylib
    │           │   │   ├── libjsdt.dylib
    │           │   │   ├── libjsig.dylib
    │           │   │   ├── libjsound.dylib
    │           │   │   ├── libkcms.dylib
    │           │   │   ├── liblcms.dylib
    │           │   │   ├── libmanagement.dylib
    │           │   │   ├── libmlib_image.dylib
    │           │   │   ├── libnet.dylib
    │           │   │   ├── libnio.dylib
    │           │   │   ├── libnpt.dylib
    │           │   │   ├── libosx.dylib
    │           │   │   ├── libosxapp.dylib
    │           │   │   ├── libosxkrb5.dylib
    │           │   │   ├── libosxui.dylib
    │           │   │   ├── libprism_common.dylib
    │           │   │   ├── libprism_es2.dylib
    │           │   │   ├── libprism_sw.dylib
    │           │   │   ├── libresource.dylib
    │           │   │   ├── libsaproc.dylib
    │           │   │   ├── libsplashscreen.dylib
    │           │   │   ├── libsunec.dylib
    │           │   │   ├── libt2k.dylib
    │           │   │   ├── libunpack.dylib
    │           │   │   ├── libverify.dylib
    │           │   │   ├── libzip.dylib
    │           │   │   ├── logging.properties
    │           │   │   ├── management
    │           │   │   │   ├── jmxremote.access
    │           │   │   │   ├── jmxremote.password.template
    │           │   │   │   ├── management.properties
    │           │   │   │   └── snmp.acl.template
    │           │   │   ├── management-agent.jar
    │           │   │   ├── meta-index
    │           │   │   ├── net.properties
    │           │   │   ├── psfont.properties.ja
    │           │   │   ├── psfontj2d.properties
    │           │   │   ├── resources.jar
    │           │   │   ├── rt.jar
    │           │   │   ├── security
    │           │   │   │   ├── US_export_policy.jar
    │           │   │   │   ├── blacklist
    │           │   │   │   ├── blacklisted.certs
    │           │   │   │   ├── cacerts
    │           │   │   │   ├── java.policy
    │           │   │   │   ├── java.security
    │           │   │   │   ├── local_policy.jar
    │           │   │   │   └── trusted.libraries
    │           │   │   ├── server
    │           │   │   │   ├── Xusage.txt
    │           │   │   │   ├── libjsig.dylib
    │           │   │   │   └── libjvm.dylib
    │           │   │   ├── sound.properties
    │           │   │   └── tzdb.dat
    │           │   └── release
    │           ├── mod-uploader.jar
    │           ├── mts-launcher.jar
    │           ├── preferences
    │           │   ├── GREMLIN
    │           │   ├── GREMLIN.backUp
    │           │   ├── OPM
    │           │   ├── OPM.backUp
    │           │   ├── STSAchievements
    │           │   ├── STSAchievements.backUp
    │           │   ├── STSBetaCardPreference
    │           │   ├── STSBetaCardPreference.backUp
    │           │   ├── STSDaily
    │           │   ├── STSDaily.backUp
    │           │   ├── STSDataDefect
    │           │   ├── STSDataDefect.backUp
    │           │   ├── STSDataTheSilent
    │           │   ├── STSDataTheSilent.backUp
    │           │   ├── STSDataVagabond
    │           │   ├── STSDataVagabond.backUp
    │           │   ├── STSGameplaySettings
    │           │   ├── STSGameplaySettings.backUp
    │           │   ├── STSInputSettings
    │           │   ├── STSInputSettings.backUp
    │           │   ├── STSInputSettings_Controller
    │           │   ├── STSInputSettings_Controller.backUp
    │           │   ├── STSPlayer
    │           │   ├── STSPlayer.backUp
    │           │   ├── STSSaveSlots
    │           │   ├── STSSaveSlots.backUp
    │           │   ├── STSSeenBosses
    │           │   ├── STSSeenBosses.backUp
    │           │   ├── STSSeenCards
    │           │   ├── STSSeenCards.backUp
    │           │   ├── STSSeenRelics
    │           │   ├── STSSeenRelics.backUp
    │           │   ├── STSSound
    │           │   ├── STSSound.backUp
    │           │   ├── STSTips
    │           │   ├── STSTips.backUp
    │           │   ├── STSUnlockProgress
    │           │   ├── STSUnlockProgress.backUp
    │           │   ├── STSUnlocks
    │           │   ├── STSUnlocks.backUp
    │           │   ├── THE_ANIMATOR
    │           │   ├── THE_ANIMATOR.backUp
    │           │   ├── THE_CURSED
    │           │   └── THE_CURSED.backUp
    │           ├── runs
    │           │   ├── DAILY
    │           │   │   └── 1561378780.run
    │           │   ├── GREMLIN
    │           │   │   └── 1561293958.run
    │           │   ├── OPM
    │           │   │   └── 1561901140.run
    │           │   ├── THE_ANIMATOR
    │           │   │   ├── 1561737675.run
    │           │   │   ├── 1561741071.run
    │           │   │   ├── 1561814116.run
    │           │   │   ├── 1561855628.run
    │           │   │   ├── 1561860642.run
    │           │   │   └── 1561898764.run
    │           │   └── THE_CURSED
    │           │       ├── 1561297930.run
    │           │       ├── 1561298785.run
    │           │       ├── 1561301923.run
    │           │       ├── 1561734545.run
    │           │       ├── 1561734989.run
    │           │       ├── 1561736311.run
    │           │       ├── 1561796312.run
    │           │       └── 1561803736.run
    │           ├── saves
    │           │   ├── DEFECT.autosave.back
    │           │   ├── DEFECT.autosaveBETA
    │           │   ├── DEFECT.autosaveBETA.backUp
    │           │   ├── IRONCLAD.autosave.back
    │           │   ├── IRONCLAD.autosaveBETA
    │           │   ├── IRONCLAD.autosaveBETA.backUp
    │           │   ├── THE_SILENT.autosaveBETA
    │           │   └── THE_SILENT.autosaveBETA.backUp
    │           ├── sendToDevs
    │           │   ├── logs
    │           │   │   ├── SlayTheSpire.log
    │           │   │   ├── SlayTheSpire_201906191258_1.log.zip
    │           │   │   ├── SlayTheSpire_201906231014_1.log.zip
    │           │   │   ├── SlayTheSpire_201906231246_1.log.zip
    │           │   │   ├── SlayTheSpire_201906231520_1.log.zip
    │           │   │   ├── SlayTheSpire_201906241220_1.log.zip
    │           │   │   ├── SlayTheSpire_201906281433_1.log.zip
    │           │   │   ├── SlayTheSpire_201906281658_1.log.zip
    │           │   │   ├── SlayTheSpire_201906290729_1.log.zip
    │           │   │   ├── SlayTheSpire_201906290819_1.log.zip
    │           │   │   ├── SlayTheSpire_201906291023_1.log.zip
    │           │   │   ├── SlayTheSpire_201906291315_1.log.zip
    │           │   │   ├── SlayTheSpire_201906300212_1.log.zip
    │           │   │   ├── SlayTheSpire_201906301246_1.log.zip
    │           │   │   ├── SlayTheSpire_201906301252_1.log.zip
    │           │   │   └── SlayTheSpire_201906301305_1.log.zip
    │           │   ├── mts_launcher.log
    │           │   └── mts_process_launch.log
    │           ├── steam_appid.txt
    │           └── twitchconfig.txt
    └── sts-fix-1.0.2.jar

30 directories, 287 files

**Comment by whwq2012** [comment]
这是目录结构，我尝试放在Slay the Spire和Contents同一层都失败了。

**Comment by NekoCaffeine** [comment]
和desktop-1.0.jar同一层

**Comment by whwq2012** [comment]
成功了，谢谢，已经成功运行，而且正常显示英文了。

**Comment by NekoCaffeine** [comment]
可以了就好了，那我睡了
